### PR TITLE
A repro for an issue with a possible incorrect dealiasing when using a service multiple times

### PR DESCRIPTION
**Pull request by hmemcpy**

### CODE REVIEW

**Review by kitlangton — APPROVED** [review]
Amazing Changes.

**Comment by kitlangton** [comment]
I accept.

**Comment by kitlangton** [comment]
You're welcome, @kitlangton.

**Comment by kitlangton** [comment]
Thank you, @kitlangton.

**Comment by hmemcpy** [comment]
Yes, thank you, @kitlangton :DD

**Pull request merged**
