### PR TITLE
add some magic

### LINKED ISSUE #13: Magic partial layer
I would like to be able to write:
```
type Requirements = ???
type LayerOutput = T1 with T2

val result: ZLayer[Requirements,Throwable,LayerOutput] = ZLayer.fromMagic[Requirements, Throwable, LayerOutput] (
  T1.live, //needs Requirements to build
  T2.live
)
```

### PR DESCRIPTION
**Pull request by senia-psm**
Add `ZLayer.fromSomeMagic[In, Out](layers...)`.

- [x] Add similar methods for `ZIO` and `ZSpec` (`ZManaged` is out of scope)
- [x] Find out what it the purpose of `DummyK`
- [x] Add documentation

Fix #13

### CODE REVIEW

**Comment by senia-psm** [comment]
@kitlangton I'd like to add partial layers (see #13 ). It seems like `ExprGraph` already supports this feature. This PR works for me, though I have a questions:
What is the purpose of `DummyK` in `ZLayer.fromMagic`? For me `sbt +test` succeeds without `DummyK` in `ZLayer.fromSomeMagic`.

**Comment by kitlangton** [comment]
@senia-psm Woo! Awesome! :D Great job! `DummyK` was seemingly necessary in order to access the type of the environment at compile time, at least for `.provideMagicLayer`. As I implemented those methods first, I must've just copy-pasted those signatures and never tried removing the Dummy. But yeah, as the type is applied directly to this method, it shouldn't need the implicit dummy.

**Review by kitlangton — APPROVED** [review]
Great job :) Thanks so much!

**Comment by kitlangton** [comment]
Since it's marked WIP, I won't merge it yet, in case you had some changes you wanted to make. But it looks great to me. So just let me know when you're happy and I'll merge it in ❤️

**Comment by senia-psm** [comment]
Ok, I'll add some other methods today.

**Comment by senia-psm** [comment]
@kitlangton not `WIP` any more

**Review by kitlangton — APPROVED** [review]
:D :D :D

**Pull request merged**
